function state = exchange_data(servos)
%UNTITLED6 此处显示有关此函数的摘要
%   此处显示详细说明
global keytable;
global controller_started;
state=zeros(54,1);

%% 与realflight建立连接
if controller_started==0
    reply=soap_request("RestoreOriginalControllerDevice", "<?xml version='1.0' encoding='UTF-8'?>\n"+...
"<soap:Envelope xmlns:soap='http://schemas.xmlsoap.org/soap/envelope/' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>\n"+...
"<soap:Body>\n"+...
"<RestoreOriginalControllerDevice><a>1</a><b>2</b></RestoreOriginalControllerDevice>\n"+...
"</soap:Body>\n"+...
"</soap:Envelope>");
    reply='';
    reply=soap_request("InjectUAVControllerInterface", "<?xml version='1.0' encoding='UTF-8'?>\n"+...
"<soap:Envelope xmlns:soap='http://schemas.xmlsoap.org/soap/envelope/' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>\n"+...
"<soap:Body>\n"+...
"<InjectUAVControllerInterface><a>1</a><b>2</b></InjectUAVControllerInterface>\n"+...
"</soap:Body>\n"+...
"</soap:Envelope>");
    reply='';
    controller_started=1;
end

%% 数据收发
scaled_servos=(servos-1000)/1000;

reply = soap_request("ExchangeData",sprintf("<?xml version='1.0' encoding='UTF-8'?><soap:Envelope xmlns:soap='http://schemas.xmlsoap.org/soap/envelope/' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>\n"+...
"<soap:Body>\n"+...
"<ExchangeData>\n"+...
"<pControlInputs>\n"+...
"<m-selectedChannels>4095</m-selectedChannels>\n"+...
"<m-channelValues-0to1>\n"+...
"<item>%.4f</item>\n"+...
"<item>%.4f</item>\n"+...
"<item>%.4f</item>\n"+...
"<item>%.4f</item>\n"+...
"<item>%.4f</item>\n"+...
"<item>%.4f</item>\n"+...
"<item>%.4f</item>\n"+...
"<item>%.4f</item>\n"+...
"<item>%.4f</item>\n"+...
"<item>%.4f</item>\n"+...
"<item>%.4f</item>\n"+...
"<item>%.4f</item>\n"+...
"</m-channelValues-0to1>\n"+...
"</pControlInputs>\n"+...
"</ExchangeData>\n"+...
"</soap:Body>\n"+...
"</soap:Envelope>",...
                               scaled_servos(1),...
                               scaled_servos(2),...
                               scaled_servos(3),...
                               scaled_servos(4),...
                               scaled_servos(5),...
                               scaled_servos(6),...
                               scaled_servos(7),...
                               scaled_servos(8),...
                               scaled_servos(9),...
                               scaled_servos(10),...
                               scaled_servos(11),...
                               scaled_servos(12)));

%% 解包
if isempty(reply)==0
    reply0=reply;
    remain=reply;
    for i=1:1:54
%         if i>45
%             disp("qq");
%         end
        index=strfind(remain,keytable(i,1));
        if isempty(index)==0
            remain=remain(index(1):strlength(remain));    
        else
%         if isempty(remain)
            index0=strfind(reply0,keytable(i,1));
            if isempty(index0)==0
                remain=reply0(index0(1):strlength(reply0));
            else
                printf("Failed to find key %s\n", keytable(i,1));
                controller_started=0;
                break;
            end      
        end
        remain=remain(strlength(keytable(i,1))+2:strlength(remain));
        v=strtok(remain, "<");
        %index1=strfind(v,keytable(i,1));
        if strfind(v,keytable(i,1))==1
            remain=remain(strlength(keytable(i,1))+3:strlength(remain));
            v=strtok(remain, "<");
        end
        if strcmp(v,"true")
            v="1";
        elseif strcmp(v,"false")
            v="0";
        end
    
        keytable(i,2)=v;
        state(i,1)=str2double(v);
    end
end
